spring:
  application:
    name: CaronaABC
  datasource:
    url: jdbc:h2:mem:carona-db
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  thymeleaf:
    cache: false

server:
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    web: DEBUG