spring:
  application:
    name: CaronaABC
#  datasource:
#    url: jdbc:h2:file:~/test
#    driverClassName: com.h2.Driver
#    username: sa
#    password:
#  jpa:
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        format_sql: true
  thymeleaf:
    cache: false

server:
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    web: DEBUG