spring:
  h2:
    console:
      enabled: true
      path: /h2
  application:
    name: CaronaABC
  datasource:
    url: jdbc:h2:file:~/test
    driverClassName: com.h2.Driver
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false

server:
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    web: DEBUG