spring:
  application:
    name: CaronaABC
  datasource:
    url: jdbc:h2:mem:carona-db
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: "/h2"

server:
  error:
    include-message: always
    include-binding-errors: always