spring:
  application:
    name: CaronaABC
  datasource:
    url: jdbc:h2:mem:carona-db
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
      show_sql: true

server:
  error:
    include-message: always
    include-binding-errors: always